version: "3.9"
services:
  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
  webserver:
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - DATASOURCE_JNDI
      - DATASOURCE_NAME
      - DB_USER
      - DB_PASS
      - DB_HOST
      - DB_PORT
      - DB_NAME
      - ECLIPSELINK_VERSION
      - WILDFLY_ADMIN_PASSWORD
      - POSTGRES_DRIVER_VERSION
      - JWT_ALGORITHM
      - JWT_ALIAS
      - JWT_KEYSIZE
      - JWT_KEYPASS
      - JWT_KEYSTORE
      - JWT_STOREPASS
      - JWT_CANONICAL_NAME
      - JWT_ORGANIZATIONAL_UNIT
      - JWT_ORGANIZATION
      - JWT_COUNTRY
      - JWT_ISSUER
      - JWT_AUDIENCE
      - JWT_REALM
    depends_on:
      - db
